version: "3.8"

services:
  my_backend:
    build: .
    container_name: backend_service
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_service
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
