const CACHE_TEMPLATE_TRIP_TIMELINE = "TEMPLATE_TRIP_TIMELINE:";
const CACHE_TEMPLATE_TRIP_ASSTIANT = "TEMPLATE_TRIP_ASSTIANT:";
const CACHE_WEATHER_FORECAST = "WEATHER_FORECAST:";

module.exports = {
  CACHE_TEMPLATE_TRIP_TIMELINE,
  CACHE_TEMPLATE_TRIP_ASSTIANT,
  CACHE_WEATHER_FORECAST,
};
