const EXPIRED_TIME_TOKEN_NOT_REMENBER = "1d";
const EXPIRED_TIME_TOKEN_REMENBER = "30d";
const TIME_CHANGE_PASSWORD = 8; // 8mins
const MAX_AGE_COOKIE = 30 * 24 * 60 * 60 * 1000;
const TIME_VERIFY_ACCOUNT = 5; // 5 mins
const MAX_SOCIAL_NETWORKS = 3;
const MAX_CALL_SUGGEST = 3;
module.exports = {
  MAX_AGE_COOKIE,
  MAX_SOCIAL_NETWORKS,
  TIME_VERIFY_ACCOUNT,
  EXPIRED_TIME_TOKEN_REMENBER,
  EXPIRED_TIME_TOKEN_NOT_REMENBER,
  TIME_CHANGE_PASSWORD,
  MAX_CALL_SUGGEST,
};
